### ISSUE TITLE
Save incoming calls

### ISSUE THREAD

**Issue by Lukas1811** [NexdApp/nexd-backend#10]
- [x] react to webhook from from twilio
- [x] get recorded call from twilio
- [x]  Make database table for entries where files are located in a AWS S3 Bucket

- [x] add database functionality to upload, store and delete files

**Comment by fanick-ber** [comment]
@Lukas1811 for the moment it is probably easiest (and not so expensive) to leave the recordings at twilio and just save the URL.

**Comment by fanick-ber** [comment]
We currently only save the url, which is fine for the moment. Will be improved later.
