### ISSUE TITLE
DELETE /help-lists/{helpListId}/help-request/{helpRequestId} doesn't reset status of the request

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-backend#110]
it seems like calling `PUT /help-lists/{helpListId}/help-request/{helpRequestId}` updates the status of a help request from pending to ongoing (which is cool!) - BUT calling `DELETE /help-lists/{helpListId}/help-request/{helpRequestId}` does not change it back to pending... - which is at least unexpected but potentially also dangerous....

**Comment by andrewBalekha** [comment]
`helpRequest.status = HelpRequestStatus.PENDING;
    helpList.helpRequests = helpList.helpRequests.filter(
      request => request.id != helpRequest.id,
    );
    return await this.helpListsRepository.save(helpList);`

helpRequest being filtered out but not saved, should it stay in helpList? Or helpRequest must be saved somehow?

**Comment by fanick-ber** [comment]
solved with https://github.com/NexdApp/nexd-backend/pull/121
