### ISSUE TITLE
Document node versions

### ISSUE THREAD

**Issue by js-kyle** [NexdApp/nexd-backend#112]
Hi there,

At the moment, the app does not start using Node14. That itself probably isn't an issue yet as it is a very new version, however, it would be good to specify what Node versions should be used, probably just by adding `engines` to the package.json file.

I can do that - I assume we are targeting Node12 as that is what the Docker container is using

**Comment by fanick-ber** [comment]
Hey, 
good catch! I have not used node14 so far. 
It would be nice, if you can create a PR with the `engines`.

We should identify the problem with node14, I assume it is not a big change to adapt.
