### ISSUE TITLE
All Response JSON of the Calls API are specified as empty JSON objects

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-backend#56]
<img width="499" alt="Bildschirmfoto 2020-04-05 um 19 42 46" src="https://user-images.githubusercontent.com/2974425/78505722-a87f1080-7775-11ea-92bd-b82740607679.png">

This causes compile issues in the iOS app when it tries to use Swagger Docs generated code

**Comment by hoppla20** [comment]
Should be fixed, if the audio endpoint is not working tell me
