### ISSUE TITLE
Plan a new article structure

### ISSUE THREAD

**Issue by fanick-ber** [NexdApp/nexd-backend#71]
Currently, articles are the most basic possible.

We want to improve this using an external API or having a better model.

**Comment by hoppla20** [comment]
First thoughts on the database models:
![articles_model](https://user-images.githubusercontent.com/25618740/79072099-77f02700-7cdf-11ea-90ae-65b4eefa147a.jpg)

**Comment by fanick-ber** [comment]
solved in #130
