### ISSUE TITLE
Add call information to HelpRequest model

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-backend#73]
In order to implement the following two screens in the "Helper" workflow

<img width="443" alt="Bildschirmfoto 2020-04-12 um 14 16 39" src="https://user-images.githubusercontent.com/2974425/79068598-6fd8bd00-7cc8-11ea-8dce-7d4622cc72fd.png">

We would need the `HelpRequest` to include information (e.g. the `Call` objecT) about the call from which it was transcripted (as long as it was created from a transcripted call - otherwise `null`)

**Comment by fanick-ber** [comment]
Should have been resolved with https://github.com/NexdApp/nexd-backend/pull/77
