### ISSUE TITLE
Mostly the HelpRequests contained in HelpLists don't contain the requester

### ISSUE THREAD

**Issue by schroepf** [NexdApp/nexd-backend#75]
I noticed a difference in behavior for the responses created by the "Help Lists" endpoint:

- `GET /help-lists`: all help requests (which are nested in the "HelpList" responses contain the correct `requester` object
- `GET /help-lists/{helpListId}`: help requests are lacking the `requestor` entirely
- `PUT /help-lists/{helpListId}/help-request/{helpRequestId}`: `requestor` is only available for the request which was added through the call.. all others are lacking the requestor.

From a "users" perspective of the API it would be cool if all the call return fully initialized responses to avoid nesting calls..

**Comment by fanick-ber** [comment]
Thanks, I think it is solved with commit https://github.com/NexdApp/nexd-backend/commit/2aa44bb03399c5a1fe79073fd6e50b6d864df627
