### ISSUE TITLE
same error response body for every body

### ISSUE THREAD

**Issue by claudius-kienle** [NexdApp/nexd-backend#89]
It would be nice to receive for every invalid request the same type of error response.
Currently in registration, if i register with an already registered email, i get:
`{"statusCode":409,"errorCode":"USERS_USER_EXISTS","errorDescription":"user is already present"}`
If i register with a too short password, i get:
`{"statusCode":400,"message":["password must be longer than or equal to 8 characters"],"error":"Bad Request"}`
(I'd prefer the 2nd one)

**Comment by andre-stefanov** [comment]
Actually the first one is correct because we can't localize the second one

**Comment by claudius-kienle** [comment]
That makes sense, so the first error response has to be migrated to the 2nd one.

**Comment by fanick-ber** [comment]
merged in https://github.com/NexdApp/nexd-backend/pull/90
Let me know, if there is still some improvement possible.
